apiVersion: v1
kind: Namespace
metadata:
  name: cluster1
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: cluster-proxy
  namespace: cluster1
spec:
  installNamespace: "open-cluster-management-cluster-proxy"
