kind: Deployment
apiVersion: apps/v1
metadata:
  name: hub-registration-controller
  namespace: open-cluster-management
  labels:
    app: hub-registration-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-registration-controller
  template:
    metadata:
      labels:
        app: hub-registration-controller
    spec:
      serviceAccountName: hub-sa
      containers:
      - name: hub-controller
        image: champly/registration:v0.0.1
        imagePullPolicy: Always
        args:
          - "/registration"
          - "controller"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
